let weatherData = [
  {
    id: 1,
    icon: "/img/weather/cloud.JPG",
    month: "December - February",
    highC: 3,
    highF: 37.4,
    lowC: -16,
    lowF: 3.2,
  },
  {
    id: 2,
    icon: "/img/weather/snow.JPG",
    month: "March - May",
    highC: 12,
    highF: 53.6,
    lowC: -7,
    lowF: 19.4,
  },
  {
    id: 3,
    icon: "/img/weather/sunny.JPG",
    month: "June - August",
    highC: 23,
    highF: 73.4,
    lowC: 1,
    lowF: 33.8,
  },
  {
    id: 4,
    icon: "/img/weather/sunny.JPG",
    month: "June - August",
    highC: 23,
    highF: 73.4,
    lowC: 1,
    lowF: 33.8,
  },
  {
    id: 5,
    icon: "/img/weather/rainy.JPG",
    month: "September - November",
    highC: 19,
    highF: 66.2,
    lowC: -7,
    lowF: 19.4,
  },
];
